name: mpesa4dart
description: A native dart package for Mpesa. There are various other Mpesa libraries, but this package uses a different approach. It does not wrap existing MPesa libraries, but instead accesses the Mpesa API directly.
version: 23.0.1
homepage: https://www.openapiportal.m-pesa.com/

environment:
  sdk: '>=2.18.6 <3.0.0'
  
dependencies:

  http: 
  meta: 
  convert: 
  encrypt: ^5.0.1
  tripledes: ^2.1.0
  basic_utils: ^5.4.2
  built_value: ^8.4.2
  built_collection: ^5.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.3
  built_value_generator: ^8.4.2
  source_gen: 
  json_serializable:
